version: '3.9'

# Services
services:

  # Nginx service
  nginx:
    build:
      context: ./bin
      dockerfile: Dockerfile-nginx
    container_name: webdev-nginx
    ports:
      - 80:80
      - 443:443
    networks:
      default:
        aliases:
          - frontend.webdev.test
    volumes:
      - ./src/backend:/var/www/backend
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - ./.docker/nginx/certs:/etc/nginx/certs
      - phpmyadmindata:/var/www/phpmyadmin
    depends_on:
      - backend
      - frontend
      - phpmyadmin

  # Backend service
  backend:
    build:
      context: ./bin
      dockerfile: Dockerfile-backend
      target: backend
    container_name: webdev-backend
    working_dir: /var/www/backend
    volumes:
      - ./src/backend:/var/www/backend
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  # Worker service
  worker:
    build:
      context: ./bin
      dockerfile: Dockerfile-backend
      target: worker
    working_dir: /var/www/backend
    volumes:
      - ./src/backend:/var/www/backend
    depends_on:
      - backend

  # Frontend service
  frontend:
    build:
      context: ./bin
      dockerfile: Dockerfile-frontend
    container_name: webdev-frontend
    working_dir: /var/www/frontend
    volumes:
      - ./src/frontend:/var/www/frontend
    depends_on:
      - backend

  # MySQL service
  mysql:
    build:
      context: ./bin
      dockerfile: Dockerfile-mysql
    container_name: webdev-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=${MYSQL_ROOT_PASSWORD}
      interval: 5s
      retries: 10

  # PhpMyAdmin
  phpmyadmin:
    build:
      context: ./bin
      dockerfile: Dockerfile-pma
    container_name: webdev-pma
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    volumes:
      - phpmyadmindata:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy

  # Ngrok Service
  ngrok:
    build:
      context: ./bin
      dockerfile: Dockerfile-ngrok
    container_name: webdev-ngrok
    ports:
      - 4040:4040
    environment:
      NGROK_PROTOCOL: http
      NGROK_PORT: nginx:443
      NGROK_AUTH: ${NGROK_AUTH}
    depends_on:
      - nginx

  # Redis Service
  redis:
    build:
      context: ./bin
      dockerfile: Dockerfile-redis
    container_name: webdev-redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data


volumes:
  mysqldata:
  phpmyadmindata:
  redisdata: