version: '3.9'

# Services
services:

  # Nginx service
  nginx:
    build:
      context: ./bin
      dockerfile: Dockerfile-nginx
    container_name: webdev-nginx
    ports:
      - 80:80
    volumes:
      - ./src/backend:/var/www/backend
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - phpmyadmindata:/var/www/phpmyadmin
    depends_on:
      - backend
      - frontend
      - phpmyadmin

  # Backend service
  backend:
    build:
      context: ./bin
      dockerfile: Dockerfile-backend
    container_name: webdev-backend
    working_dir: /var/www/backend
    volumes:
      - ./src/backend:/var/www/backend
    depends_on:
      mysql:
        condition: service_healthy

  # Frontend service
  frontend:
    build:
      context: ./bin
      dockerfile: Dockerfile-frontend
    container_name: webdev-frontend
    working_dir: /var/www/frontend
    volumes:
      - ./src/frontend:/var/www/frontend
    depends_on:
      - backend

  # MySQL service
  mysql:
    build:
      context: ./bin
      dockerfile: Dockerfile-mysql
    container_name: webdev-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=${MYSQL_ROOT_PASSWORD}
      interval: 5s
      retries: 10

  # PhpMyAdmin
  phpmyadmin:
    build:
      context: ./bin
      dockerfile: Dockerfile-pma
    container_name: webdev-pma
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    volumes:
      - phpmyadmindata:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysqldata:
  phpmyadmindata: