version: '3.9'

# Services
services:

  # Nginx service
  nginx:
    build:
      context: ./bin
      dockerfile: Dockerfile-nginx
    container_name: webdev-nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/php
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php

  # PHP service
  php:
    build:
      context: ./bin
      dockerfile: Dockerfile-php
    container_name: webdev-php
    working_dir: /var/www/php
    volumes:
      - ./src:/var/www/php
    depends_on:
      mysql:
        condition: service_healthy

  # MySQL service
  mysql:
    build:
      context: ./bin
      dockerfile: Dockerfile-mysql
    container_name: webdev-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=${MYSQL_ROOT_PASSWORD}
      interval: 5s
      retries: 10

  # PhpMyAdmin
  phpmyadmin:
    build:
      context: ./bin
      dockerfile: Dockerfile-pma
    container_name: webdev-pma
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysqldata: